$(document).ready(function(){$('input:radio[id\x3d"mmy"]').click(function(){$("#militaryStatus").attr("disabled",false)});$('input:radio[id\x3d"mmn"]').click(function(){$("#militaryStatus").attr("disabled",true)});if($('input:radio[id\x3d"mmn"]').is(":checked"))$("#militaryStatus").attr("disabled",true);$('input:radio[id\x3d"profile.customer.militaryMemberShip1"]').click(function(){$("#militaryStatus").attr("disabled",false)});$('input:radio[id\x3d"profile.customer.militaryMemberShip2"]').click(function(){$("#militaryStatus").attr("disabled",
true)});if($('input:radio[id\x3d"profile.customer.militaryMemberShip2"]').is(":checked"))$("#militaryStatus").attr("disabled",true);$("aria-disabled","true").attr("aria-hidden","true")});
function ajaxPost(serviceURL,form,target,method,funcInSuccessCallback,errorCallback,datatype,funcInCallback,funcInCallbackParam,timeoutValue){successCallback=function(data,textStatus,jqXHR){var $response=$(data);var result=$("#errorPage",data);if(result.length!=0){document.open();document.write(data);document.close()}else if(funcInSuccessCallback)funcInSuccessCallback(data);else $("#"+target).html(data)};if(!errorCallback)errorCallback=function(xhr,ajaxOptions,thrownError){$.ajax({url:getContextPath()+
"/public/errorcontroller/error",type:"POST",dataType:"html",data:"data\x3d"+xhr.responseText,success:function(data){document.open();document.write(data);document.close()},async:true,cache:false})};if(!timeoutValue)timeoutValue=3E5;if(!method)method="post";if(!datatype)datatype="html";$.ajax({url:serviceURL,type:method,dataType:datatype,data:form,success:successCallback,error:errorCallback,timeout:timeoutValue,async:true})}
function toggleFeeWaivedReasonCode(feeWaived,index){jqFeeWaivedReasonCodeDiv=$("#feeWaivedReasonCodeDiv"+index);jqfeeWaivedReasonCodeSelect=$("#feeWaivedReasonCodeSelect"+index);jqfeeWaivedReasonTextTA=$("#feeWaivedReasonTextTA"+index);if(feeWaived)jqFeeWaivedReasonCodeDiv.show();else{jqFeeWaivedReasonCodeDiv.hide();jqfeeWaivedReasonCodeSelect.val("Select");jqfeeWaivedReasonTextTA.val("")}}
function toggleOtherReason(reasonCode,index){jqfeeWaivedReasonTextDiv=$("#feeWaivedReasonTextDiv"+index);jqfeeWaivedReasonTextTA=$("#feeWaivedReasonTextTA"+index);if(reasonCode=="30")jqfeeWaivedReasonTextDiv.show();else{jqfeeWaivedReasonTextDiv.hide();jqfeeWaivedReasonTextTA.val("")}}function transformDate(newPattern,oldPattern,dateText){return $.datepicker.formatDate(newPattern,$.datepicker.parseDate(oldPattern,dateText))}
$(document).ready(function(){$(".phonevalidate").keyup(function(){$(this).val($(this).val().replace(/[^\d]/g,""))});$(".middlenamevalidate").keyup(function(){$(this).val($(this).val().replace(/[^a-zA-Z]/g,""))})});var $errorblock=$(".errorblock");$.validator.setDefaults({errorElement:"span",errorClass:"errorMessage",highlight:function(element){$(element).closest(".control-group").addClass("error")},errorPlacement:function(error,element){error.appendTo($(element).closest(".controls"))}});
var validator=$(".registration-form").not(".ajax").find("form").validate({submitHandler:function(form){form.submit()},groups:{dateOfBirth:"birthMonth birthDay birthYear"},success:function(element){$(element).closest(".control-group").removeClass("error");if(validator.numberOfInvalids()==0)$errorblock.addClass("hidden")},invalidHandler:function(){$errorblock.removeClass("hidden")}});
function messenger(){var key=arguments[0];var msg=messages[key];for(var i=1;i<arguments.length;i++)msg=msg.replace(new RegExp("\\{"+(i-1)+"\\}","gm"),arguments[i]);return msg}
var messages={"msg.test.testMessage":"This is a test.","msg.test.center.search.label.getDirection":"Get Directions","msg.test.center.search.label.callToSchedule":"Please call the test center to schedule appointment(s).","msg.test.center.search.label.scheduleAppointment":"Schedule Appointment","error.order.issue.refund.refundableOrderItemRequired":"Please select an order item to provide refund.","error.order.issue.refund.refundAmountRequired":"Please enter valid Refund Amount.","error.order.issue.refund.refundAmountOnlyNumber":"Please enter only number for Refund Amount.",
"error.order.issue.refund.refundAmountInvalid":"Refund Amount provided is invalid.","error.order.issue.refund.refundAmountExceeded":"Refund Amount is more than the max allowed refund amount.","error.order.issue.refund.refundReasonCodeRequired":"Please select the Refund Reason code.","error.register.password.required":"Please enter the password.","msg.test.center.search.label.checkLaterToSchedule":"Please check later to schedule appointment(s)."};var eregMsgsJSON=eregMsgsJSON||{};
var eregMessagesCacheVersion="2";
function loadEregMsgsByPattern(keyPattern,updateLocalStorageFlag,csrFlag){try{if(keyPattern===undefined||keyPattern===null||keyPattern.trim()===""){console.log("loadEregMsgsByPattern invalid args:",keyPattern);return}var storedMessages=sessionStorage.getItem("eregMsgsJSON");var storedLanguage=sessionStorage.getItem("eregMsgsLanguage");var storedVersion=sessionStorage.getItem("eregMsgsVersion");var pageLanguage=$("html").attr("lang");if(!storedMessages||pageLanguage!==storedLanguage||storedVersion!==
eregMessagesCacheVersion)$.ajax({url:getContextPath()+(csrFlag?"/csr/public/eregmessages":"/public/eregmessages"),type:"GET",data:{keyPattern:keyPattern.trim()},dataType:"json",async:false,cache:true,success:function(response){if(!response||!response.data){console.error("Please load the EregMessages before using them.");return}eregMsgsJSON=response.data;if(updateLocalStorageFlag){sessionStorage.setItem("eregMsgsJSON",JSON.stringify(eregMsgsJSON));sessionStorage.setItem("eregMsgsLanguage",pageLanguage);
sessionStorage.setItem("eregMsgsVersion",eregMessagesCacheVersion)}}})}catch(error){console.log(error)}}
function getEregMsgByCode(){if(arguments.length===0){console.log("getEregMsgByCode key is undefined");return}if($.isEmptyObject(eregMsgsJSON)){var storedMessages=sessionStorage.getItem("eregMsgsJSON");eregMsgsJSON=storedMessages?JSON.parse(storedMessages):null;if(eregMsgsJSON===undefined||eregMsgsJSON===null){console.error("Please load the EregMessages before using them.");return null}}var message=eregMsgsJSON[arguments[0]];if(message===undefined||message===null)return null;try{var argumentIndex=
0;for(var i=1;i<arguments.length;i++){var values=Array.isArray(arguments[i])?arguments[i]:[arguments[i]];for(var j=0;j<values.length;j++){if(values[j])message=message.replace(new RegExp("\\{"+argumentIndex+"\\}","ig"),values[j]);argumentIndex++}}}catch(error){console.log("Error in replacing the args.",error)}return message}function getContextPath(){return $("meta[name\x3d'contextPath']").attr("content")}
function getURLParameter(name){return decodeURIComponent(((new RegExp("[?|\x26]"+name+"\x3d"+"([^\x26;]+?)(\x26|#|;|$)")).exec(location.search)||[,""])[1].replace(/\+/g,"%20"))||null}function stringToFinancialNumber(value){return parseFloat(parseFloat(value).toFixed(2))};